# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-27 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('code', models.CharField(db_column='CODIGO_RESERVA', max_length=18, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField(db_column='FECHA_ENTRADA')),
                ('check_out', models.DateTimeField(db_column='FECHA_SALIDA')),
                ('name', models.CharField(db_column='NOMBRE', max_length=50)),
                ('last_name', models.CharField(db_column='APELLIDO', max_length=50)),
                ('phone', models.CharField(db_column='TELEFONO', max_length=20)),
                ('email', models.CharField(db_column='EMAIL', max_length=50)),
                ('observations', models.CharField(db_column='OBSERVACIONES', max_length=200)),
                ('card_payment_holder', models.CharField(db_column='TITULAR_TARJETA', max_length=100)),
                ('card_payment_type', models.CharField(choices=[('VISA', 'VISA'), ('MATERD_CARD', 'MASTER CARD'), ('AMERICAN_EXPRESS', 'AMERICAN EXPRESS'), ('DINNERS_CLUB', 'DINNERS CLUB')], db_column='TARJETA_TIPO', default='VISA', max_length=20)),
                ('card_payment_number', models.CharField(db_column='TARJETA_NUMERO', max_length=20)),
                ('card_paymeny_expiration_month', models.IntegerField(db_column='TARJETA_MES_CADUCIDAD')),
                ('card_paymeny_expiration_year', models.IntegerField(db_column='TARJETA_A\xd1O_CADUCIDAD')),
                ('card_paymeny_cvc', models.CharField(db_column='TARJETA_CVC', max_length=4)),
                ('created_date', models.DateTimeField(db_column='FECHA_CREA', editable=False)),
                ('updated_date', models.DateTimeField(db_column='FECHA_MODIFICA', editable=False, null=True)),
                ('room', models.ForeignKey(db_column='HABITACION_ID', on_delete=django.db.models.deletion.PROTECT, to='rooms.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RESERVAS',
                'verbose_name': 'Reserva',
            },
        ),
    ]
