# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-27 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='card_payment_type',
            field=models.CharField(choices=[('V', 'VISA'), ('MC', 'MASTER CARD'), ('AE', 'AMERICAN EXPRESS'), ('DC', 'DINNERS CLUB')], db_column='TARJETA_TIPO', default='V', max_length=4),
        ),
    ]
