# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20190427_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='card_paymeny_cvc',
            new_name='card_payment_cvc',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='card_paymeny_expiration_month',
            new_name='card_payment_expiration_month',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='card_paymeny_expiration_year',
            new_name='card_payment_expiration_year',
        ),
        migrations.AlterField(
            model_name='booking',
            name='observations',
            field=models.CharField(db_column='OBSERVACIONES', max_length=200, null=True),
        ),
    ]
