# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-27 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20190427_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(db_column='FECHA_ENTRADA'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(db_column='FECHA_SALIDA'),
        ),
    ]
