# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-28 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20190427_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.DecimalField(db_column='VALOR_TOTAL', decimal_places=2, default=0, max_digits=18, verbose_name='total'),
        ),
    ]
