# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-28 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='card_payment_cvc',
            field=models.CharField(max_length=4, verbose_name='CVC'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='card_payment_expiration_month',
            field=models.IntegerField(verbose_name='Tarjeta mes caducidad'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='card_payment_expiration_year',
            field=models.IntegerField(verbose_name='Tarjeta a\xf1o caducidad'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='card_payment_holder',
            field=models.CharField(max_length=100, verbose_name='Titular tarjeta'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='card_payment_number',
            field=models.CharField(max_length=20, verbose_name='Tarjeta n\xfamero'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='card_payment_type',
            field=models.CharField(choices=[('V', 'VISA'), ('MC', 'MASTER CARD'), ('AE', 'AMERICAN EXPRESS'), ('DC', 'DINNERS CLUB')], default='V', max_length=4, verbose_name='Tipo tarjeta'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(verbose_name='Fecha entrada'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(verbose_name='Fecha salida'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='C\xf3digo reserva'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_date',
            field=models.DateTimeField(editable=False, verbose_name='Fecha creaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='observations',
            field=models.CharField(max_length=200, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.Room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Fecha actualizaci\xf3n'),
        ),
    ]
