# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.AutoField(db_column='HABITACION_ID', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='TIPO_HABITACION', max_length=20)),
                ('guest', models.IntegerField(db_column='MAXIMO_PERSONAS')),
                ('value', models.DecimalField(db_column='VALOR_DIA', decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'HABITACIONES',
                'verbose_name': 'Habitacion',
            },
        ),
    ]
