# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-27 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.IntegerField(choices=[(1, 'Individual'), (2, 'Doble'), (3, 'Triple'), (4, 'Cuadruple')], db_column='TIPO_HABITACION', default=1),
        ),
    ]
