# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-27 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20190427_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.IntegerField(db_column='DISPONIBILIDAD', default=0),
        ),
    ]
