# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-27 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Habitacion', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.IntegerField(db_column='DISPONIBILIDAD', default=0, verbose_name='Disponibles'),
        ),
        migrations.AlterField(
            model_name='room',
            name='guest',
            field=models.IntegerField(db_column='MAXIMO_PERSONAS', verbose_name='M\xe1ximo personas'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.IntegerField(choices=[(1, 'Individual'), (2, 'Doble'), (3, 'Triple'), (4, 'Cuadruple')], db_column='TIPO_HABITACION', default=1, unique=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='room',
            name='value',
            field=models.DecimalField(db_column='VALOR_DIA', decimal_places=2, max_digits=18, verbose_name='Valor por d\xeda'),
        ),
    ]
